name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.100'  # Use the appropriate version

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release

      - name: Run Tests
        run: dotnet test

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: publish
          path: ./path/to/your/publish/folder

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: publish
          path: ./path/to/your/publish/folder

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "jkonrad14159@gmail.com"
          git config --global user.name "Jason Willis"
          git clone --branch=gh-pages https://github.com/${{ github.repository }}.git gh-pages
          cp -R ./path/to/your/publish/folder/* ./gh-pages/
          cd gh-pages
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages
